# Q2

In [29]:
import numpy as np
from sklearn.linear_model import LinearRegression , Ridge
from numpy.linalg import inv
np.set_printoptions(suppress=True)

In [30]:
X = np.array([[1, 5], [2, 6], [2, 10], [2, 12], [3, 17], [3, 12], [4, 6], [4, 5], [4, 7], [5, 10]])
y = np.array([10, 40, 50, 60, 70, 50, 30, 20, 40, 70])

In [32]:
X_ = np.c_[ X, np.ones(10) ] # [X|1]
X_

array([[ 1.,  5.,  1.],
       [ 2.,  6.,  1.],
       [ 2., 10.,  1.],
       [ 2., 12.,  1.],
       [ 3., 17.,  1.],
       [ 3., 12.,  1.],
       [ 4.,  6.,  1.],
       [ 4.,  5.,  1.],
       [ 4.,  7.,  1.],
       [ 5., 10.,  1.]])

In [33]:
XXT= np.matmul(X_.T,X_) # X.transpose(X)
XXT

array([[104., 270.,  30.],
       [270., 948.,  90.],
       [ 30.,  90.,  10.]])

In [34]:
XXT_inv = inv(XXT) # inverse(X.transpose(X))
XXT_inv

array([[ 0.07142857, -0.        , -0.21428571],
       [ 0.        ,  0.00724638, -0.06521739],
       [-0.21428571, -0.06521739,  1.32981366]])

In [35]:
theta = np.matmul(XXT_inv,np.matmul(X_.T,y)) # theta = inverse(X.transpose(X)) . transpose(X) . Y
theta

array([ 4.28571429,  4.34782609, -7.98757764])

# Q3(a)

In [38]:
regressor = LinearRegression().fit(X, y)
print('theta =', np.append(regressor.coef_, regressor.intercept_))

theta = [ 4.28571429  4.34782609 -7.98757764]


# Q3(b),Q4

In [42]:
point1=np.array([[3,16]])
point2=np.array([[2,4]])
point3=np.array([[5,4]])

print("Normal Regressor coefficient(theta) = ",np.append(regressor.coef_, regressor.intercept_))
y1 = regressor.predict(point1)
y2 = regressor.predict(point2)
y3 = regressor.predict(point3)
print('Point1 pred =',y1,'--- Point2 pred =',y2,'--- Point3 pred =',y3,"\n")

for alpha in [0.1,1,10,100]:
   regressor_clf = Ridge(alpha=alpha).fit(X, y)
   print('coefficient(theta) with alpha {} ='.format(alpha), np.append(regressor_clf.coef_, regressor_clf.intercept_))
   
   #Q4 
   y1 = regressor_clf.predict(point1)
   y2 = regressor_clf.predict(point2)
   y3 = regressor_clf.predict(point3)
   print('Point1 pred =',y1,'--- Point2 pred =',y2,'--- Point3 pred =',y3,"\n")

Normal Regressor coefficient(theta) =  [ 4.28571429  4.34782609 -7.98757764]
Point1 pred = [74.43478261] --- Point2 pred = [17.97515528] --- Point3 pred = [30.83229814] 

coefficient(theta) with alpha 0.1 = [ 4.25531915  4.34467777 -7.86805737]
Point1 pred = [74.41274439] --- Point2 pred = [18.021292] --- Point3 pred = [30.78724945] 

coefficient(theta) with alpha 1 = [ 4.          4.31654676 -6.84892086]
Point1 pred = [74.21582734] --- Point2 pred = [18.41726619] --- Point3 pred = [30.41726619] 

coefficient(theta) with alpha 10 = [2.5        4.05405405 0.01351351]
Point1 pred = [72.37837838] --- Point2 pred = [21.22972973] --- Point3 pred = [28.72972973] 

coefficient(theta) with alpha 100 = [ 0.52631579  2.5210084  19.731977  ]
Point1 pred = [61.64705882] --- Point2 pred = [30.86864219] --- Point3 pred = [32.44758956] 

